name: Secrets Management Workflow
version: 1.0.0
description: Manage secrets rotation and access
author: Grok Workflow System
created_at: 2024-01-22T00:00:00Z

triggers:
  - on_schedule:
      cron: "0 0 * * 0"  # Weekly
  - on_manual

steps:
  - name: inventory-secrets
    action: secrets.list_secrets
    outputs: [secrets_inventory, rotation_status]

  - name: check-expiration
    action: secrets.check_expiration
    needs: [inventory-secrets]
    params:
      warning_threshold: "30d"
    outputs: [expiring_secrets, expired_secrets]

  - name: rotate-secrets
    action: secrets.rotate
    needs: [check-expiration]
    params:
      secrets: "{{outputs.check-expiration.expiring_secrets}}"
    outputs: [rotation_results]

  - name: update-applications
    action: secrets.update_applications
    needs: [rotate-secrets]
    params:
      rotation_results: "{{outputs.rotate-secrets.rotation_results}}"
    outputs: [application_updates]

  - name: verify-secrets
    action: secrets.verify_rotation
    needs: [update-applications]
    params:
      rotated_secrets: "{{outputs.rotate-secrets.rotated_secrets}}"
    outputs: [verification_results]

  - name: audit-access
    action: secrets.audit_access
    needs: [inventory-secrets]
    params:
      period: "30d"
    outputs: [access_log, unusual_access]

  - name: revoke-unused-secrets
    action: secrets.revoke_unused
    needs: [audit-access]
    params:
      unused_threshold: "90d"
    outputs: [revoked_secrets]

  - name: generate-report
    action: reporter.generate_secrets_report
    needs: [rotate-secrets, audit-access]
    outputs: [secrets_report]

  - name: notify-owners
    action: notification.notify_secret_owners
    needs: [expiring_secrets, revoked_secrets]
    params:
      expiring: "{{outputs.check-expiration.expiring_secrets}}"
      revoked: "{{outputs.revoke-unused-secrets.revoked_secrets}}"
