name: Vulnerability Scan Workflow
version: 1.0.0
description: Automated security vulnerability scanning
author: Grok Workflow System
created_at: 2024-01-22T00:00:00Z

triggers:
  - on_schedule:
      cron: "0 0 * * 0"  # Weekly Sunday midnight
  - on_manual

steps:
  - name: define-scope
    action: security.define_scope
    outputs: [scan_scope, target_systems]

  - name: dependency-scan
    action: security.scan_dependencies
    needs: [define-scope]
    params:
      tools: ["snyk", "npm audit", "safety"]
    outputs: [dependency_vulnerabilities]

  - name: container-scan
    action: security.scan_containers
    needs: [define-scope]
    params:
      images: ["*"]
    outputs: [container_vulnerabilities]

  - name: secret-scan
    action: security.scan_secrets
    needs: [define-scope]
    params:
      patterns: ["api_key", "password", "token"]
    outputs: [secrets_found]

  - name: code-scan
    action: security.scan_code
    needs: [define-scope]
    params:
      tools: ["bandit", "eslint", "sonarqube"]
    outputs: [code_vulnerabilities]

  - name: infrastructure-scan
    action: security.scan_infrastructure
    needs: [define-scope]
    params:
      tools: ["terrascan", "kube-bench"]
    outputs: [infra_vulnerabilities]

  - name: aggregate-results
    action: security.aggregate_findings
    needs: [dependency-scan, container-scan, secret-scan, code-scan, infrastructure-scan]
    outputs: [all_vulnerabilities, severity_breakdown]

  - name: generate-report
    action: reporter.generate_vulnerability_report
    needs: [aggregate-results]
    outputs: [vuln_report]

  - name: create-tickets
    action: tracker.create_issues
    needs: [generate-report]
    params:
      severity_threshold: high
      project: security
    outputs: [ticket_ids]

  - name: notify-team
    action: notification.alert
    needs: [generate-report]
    params:
      severity: info
      message: "Weekly vulnerability scan complete"
