#!/usr/bin/env bash
#
# Rule Validator - Validates all rule files in the rules directory
#

set -e

RULES_DIR="rules"
REPORT_FILE="reports/rule-validation-report.md"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔍 Rule Validator${NC}"
echo "================================"

# Create reports directory if it doesn't exist
mkdir -p reports

# Initialize report
cat > "$REPORT_FILE" << 'EOF'
# Rule Validation Report

## Summary

| Metric | Count |
|--------|-------|
EOF

total_rules=0
valid_rules=0
invalid_rules=0
errors=()

# Function to validate a rule file
validate_rule() {
    local file="$1"
    local category="$2"
    local filename=$(basename "$file")
    local relative_path="${category}/${filename}"

    ((total_rules++))

    # Check if file has content
    if [ ! -s "$file" ]; then
        ((invalid_rules++))
        errors+=("[$relative_path] File is empty")
        echo -e "${RED}✗ $relative_path (empty)${NC}"
        return 1
    fi

    # Check for required sections
    local has_title=false
    local has_content=false

    if grep -q "^# " "$file"; then
        has_title=true
    fi

    if [ $(wc -l < "$file") -gt 5 ]; then
        has_content=true
    fi

    if [ "$has_title" = false ]; then
        ((invalid_rules++))
        errors+=("[$relative_path] Missing title (# Header)")
        echo -e "${RED}✗ $relative_path (no title)${NC}"
        return 1
    fi

    if [ "$has_content" = false ]; then
        ((invalid_rules++))
        errors+=("[$relative_path] Content too short (< 5 lines)")
        echo -e "${RED}✗ $relative_path (too short)${NC}"
        return 1
    fi

    # Check for markdown structure
    if ! grep -q "^## " "$file" && ! grep -q "^### " "$file"; then
        echo -e "${YELLOW}⚠ $relative_path (no subsections)${NC}"
    fi

    ((valid_rules++))
    echo -e "${GREEN}✓ $relative_path${NC}"
    return 0
}

# Find and validate all rule files
rule_files=$(find "$RULES_DIR" -name "*.md" -type f | sort)

if [ -z "$rule_files" ]; then
    echo -e "${RED}No rule files found in $RULES_DIR${NC}"
    exit 1
fi

# Count by category
core_count=$(find "$RULES_DIR/core-rules" -name "*.md" 2>/dev/null | wc -l)
domain_count=$(find "$RULES_DIR/domain-rules" -name "*.md" 2>/dev/null | wc -l)
agent_count=$(find "$RULES_DIR/agent-rules" -name "*.md" 2>/dev/null | wc -l)

echo ""
echo -e "${BLUE}Categories:${NC}"
echo "  Core Rules: $core_count"
echo "  Domain Rules: $domain_count"
echo "  Agent Rules: $agent_count"
echo ""

echo -e "${BLUE}Validating rules...${NC}"
echo "--------------------------------"

# Process each rule file
for file in $rule_files; do
    category=$(basename $(dirname "$file"))
    validate_rule "$file" "$category"
done

echo ""
echo "--------------------------------"
echo -e "Total: $total_rules | Valid: $valid_rules | Invalid: $invalid_rules"

# Generate detailed report
cat >> "$REPORT_FILE" << EOF
| Total Rules | $total_rules |
| Valid Rules | $valid_rules |
| Invalid Rules | $invalid_rules |
| Core Rules | $core_count |
| Domain Rules | $domain_count |
| Agent Rules | $agent_count |

## Categories

### Core Rules ($core_count files)
EOF

for file in "$RULES_DIR"/core-rules/*.md; do
    [ -f "$file" ] && echo "- [ ] $(basename "$file" .md)" >> "$REPORT_FILE"
done

cat >> "$REPORT_FILE" << EOF

### Domain Rules ($domain_count files)
EOF

for file in "$RULES_DIR"/domain-rules/*.md; do
    [ -f "$file" ] && echo "- [ ] $(basename "$file" .md)" >> "$REPORT_FILE"
done

cat >> "$REPORT_FILE" << EOF

### Agent Rules ($agent_count files)
EOF

for file in "$RULES_DIR"/agent-rules/*.md; do
    [ -f "$file" ] && echo "- [ ] $(basename "$file" .md)" >> "$REPORT_FILE"
done

# Add errors section if any
if [ ${#errors[@]} -gt 0 ]; then
    cat >> "$REPORT_FILE" << EOF

## Issues Found

EOF
    for error in "${errors[@]}"; do
        echo "- $error" >> "$REPORT_FILE"
    done
fi

cat >> "$REPORT_FILE" << EOF

## Generated
$(date)

---
*Report generated by Awesome-Grok-Workflows Rule Validator*
EOF

echo ""
echo -e "${BLUE}📄 Report saved to: $REPORT_FILE${NC}"

# Exit with error if any invalid rules found
if [ $invalid_rules -gt 0 ]; then
    echo ""
    echo -e "${RED}❌ Validation failed: $invalid_rules invalid rules found${NC}"
    exit 1
else
    echo ""
    echo -e "${GREEN}✅ All rules are valid!${NC}"
    exit 0
fi
